version: '3.0'

services:

  http:
    build: images/php-apache/
    container_name: ptm-http
    restart: always
    ports:
      - 8091:80
    volumes:
      - ../:/var/www/html
      - ./configs/PostTasksManager/db.php:/var/www/html/config/db.php

#    command: >
#        bash -c "
#        composer install &&
#        npm install &&
#        apache2-foreground"

    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: ptm-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: post-tasks-manager
      MYSQL_USER: ptm
      MYSQL_PASSWORD: ptm

  mysql-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ptm-mysql-phpmyadmin
    ports:
      - 5051:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
